name: Publish Docker image

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    push_to_registry:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        steps:
        -   name: Check out the repo
            uses: actions/checkout@v2

        -   name: Log in to Docker Hub
            uses: docker/login-action@v1 
            with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        -   name: Build and push Docker image
            uses: docker/build-push-action@v2
            with:
                context: ./backend
                push: true
                tags: ${{secrets.DOCKER_HUB_USERNAME}}/rucoresbackend:latest
        
        -   name: Run the Docker image
            #Run the container using compose up, wait for 20 seconds, and then compose down
            #The -d allows for the compose to happen in the background and more terminal
            #commands can be run. The show logs show the output of the containers in the 
            #background 
            run: |
                docker compose up --build -d 
                sleep 20 
            working-directory: ./backend
        
        -   name: Show logs 
            run: |
                docker compose logs
            working-directory: ./backend

        -   name: Stop the Docker image
            run: |
                docker compose down
            working-directory: ./backend
            