name: Publish Docker image

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    push_to_registry:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        steps:
        -   name: Check out the repo
            uses: actions/checkout@v2

        -   name: Log in to Docker Hub
            uses: docker/login-action@v1 
            with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        -   name: Build and push Docker image
            uses: docker/build-push-action@v2
            with:
                context: ./backend
                push: true
                tags: ${{secrets.DOCKER_HUB_USERNAME}}/rucoresbackend:latest
        
        -   name: Run the Docker image
            #Run the container using compose up, wait for 20 seconds, and then compose down
            run: |
                docker-compose -f docker-compose.yml up 
                sleep 10
                docker-compose -f docker-compose.yml down
